# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "controller" do |controller|
		controller.vm.box = "ubuntu/trusty64"
		controller.vm.hostname = "controller.rvkmr"
  		controller.vm.synced_folder "/home/rwagh/vagrant_machines/k8s/k8s_ubuntu/controller/", "/home/vagrant/controller"
  		controller.vm.provision "shell", inline: <<-SHELL
   			apt-get update
   		SHELL
	end
	config.vm.define "node1" do |node1|
		node1.vm.box = "ubuntu/trusty64"
		node1.vm.hostname = "node1.rvkmr"
  		node1.vm.synced_folder "/home/rwagh/vagrant_machines/k8s/k8s_ubuntu/node1/", "/home/vagrant/node1"
  		node1.vm.provision "shell", inline: <<-SHELL
   			apt-get update
   		SHELL
	end
	config.vm.define "node2" do |node2|
		node2.vm.box = "ubuntu/trusty64"
		node2.vm.hostname = "node2.rvkmr"
  		node2.vm.synced_folder "/home/rwagh/vagrant_machines/k8s/k8s_ubuntu/node2/", "/home/vagrant/node2"
  		node2.vm.provision "shell", inline: <<-SHELL
   			apt-get update
   		SHELL
	end

end
